### ISSUE TITLE
Invite existing Electron translators to participate

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#11]
We haven't made much noise about this new i18n project yet. 🙊

So far, only people paying extra-close attention have noticed and jumped in. As we get closer to being ready to expand this effort, we should reach out to the 100+ people who have already submitted translation PRs to electron/electron.

The [electron/electron-translators](https://github.com/electron/electron-translators) project exists to collect the github usernames of those folks, so we can reach out to them.

The node project creates a [GitHub team for each locale](https://github.com/orgs/nodejs/teams):

<a href="https://github.com/orgs/nodejs/teams">
<img width="802" alt="screen shot 2017-06-12 at 3 40 07 pm" src="https://user-images.githubusercontent.com/2289/27058347-8c19bb5e-4f85-11e7-854c-84cf0193fc27.png">
</a>

...we could copy this model if necessary.

**Comment by zeke** [comment]
Just invited every non-hubber who has touched `/docs-translations`  to join the new @electron/i18n team.

<img width="1042" alt="screen shot 2017-07-03 at 10 14 05 am" src="https://user-images.githubusercontent.com/2289/27802412-81eb896a-5fd8-11e7-8e6b-355e4282b172.png">

**Comment by matiasinsaurralde** [comment]
Thank you guys, just received the invitation, would love to contribute more.

**Comment by zeke** [comment]
Welcome, @matiasinsaurralde! Take a look at this repo's README for details, or jump right in at https://crowdin.com/project/electron

**Comment by sotayamashita** [comment]
@zeke Thank you for inviting me the org. I agree that electron i18n adopt the Node.js model but I think even if there is the model, we need the way to keep people motivated. 

@watilde What do you think?

**Comment by zeke** [comment]
> keep people motivated

Great point. I think we can find interesting ways to "[game-ify](https://en.wikipedia.org/wiki/Gamification)" the translation process. Crowdin has some [APIs](https://support.crowdin.com/api/info/) for fetching stats on each language. We could set up a page on the website or a periodic email or something that notifies folks about the progress for each language.

Do you have ideas about how to keep people motivated?

**Comment by sotayamashita** [comment]
>  We could set up a page on the website or a periodic email or something that notifies folks about the progress for each language.

Sound good! 

> Do you have ideas about how to keep people motivated?

What about to list contributors icon on bottom of page such as webpack, [ref](https://webpack.js.org/configuration/). 

<img width="836" alt="screen shot 2017-07-04 at 1 46 09 pm" src="https://user-images.githubusercontent.com/1587053/27815450-37d3b180-60bf-11e7-90a8-2acc2e44a3fd.png">

**Comment by zeke** [comment]
This happened! https://github.com/orgs/electron/teams/i18n/members

84 members and 39 pending invitations.

**Comment by zeke** [comment]
> We could set up a page on the website or a periodic email or something that notifies folks about the progress for each language.

That page exists now too: https://electronjs.org/languages
