### ISSUE TITLE
Continually re-apply existing translations from Translation Memory

### ISSUE THREAD

**Issue by demopark** [electron/electron-i18n#135]
Why did the Chinese translation progress on the Crowdin rollback?  The progress from 29% to 25% and lost some translation?

like this [file](https://github.com/electron/electron-i18n/commit/645ac287a6d54c97f8a573d1c0aa343742c69e32#diff-20339233aa1b3425f001bfe98f8e7c86)
with [pull#132](https://github.com/electron/electron-i18n/pull/132)

**Comment by zeke** [comment]
Hey @demopark. Sorry for the delay getting back to you on this.

This change happened probably happened in #130, when I updated the docs to a newer version of Electron. I think there's a way to automatically re-apply saved translations from the translation memory in Crowdin. I will ask their team about it.

**Comment by Andrulko** [comment]
Hi @demopark and @zeke,

Translations were indeed lost during recent source files update. They were removed not only in Chinese, but all languages. All translations are kept in the Translation Memory of course and can be quickly restored by the project manager via Pre-Translation feature:
https://support.crowdin.com/translation-memory/#applying-translation-memory-via-pre-translation

My colleagues will reach you soon and provide more details on how you can automate the process of pre-translation, so previously translated strings will remain translated.

**Comment by zeke** [comment]
I just followed the steps here for `zh-CN`: https://support.crowdin.com/translation-memory/#applying-translation-memory-via-pre-translation

The result:

<img width="1040" alt="screen shot 2017-11-10 at 11 52 30 am" src="https://user-images.githubusercontent.com/2289/32676027-e608a1b2-c60d-11e7-8a14-0b21c72281ad.png">

Let's see if this generates a new pull request with updates.

**Comment by zeke** [comment]
It looks like this worked: https://github.com/electron/electron-i18n/pull/142

Now I just need to set up a "workflow" on Crowdin to make this happen automatically.

**Comment by demopark** [comment]
@zeke That looks great , Thanks!

**Comment by zeke** [comment]
I've created a [Crowdin workflow](https://support.crowdin.com/advanced-workflows/) for this. Going to leave this issue open until I can confirm that it's working properly.

**Comment by zeke** [comment]
This appears to be working, but had some unintended side-effects: https://github.com/electron/electronjs.org/pull/947#issuecomment-350393818 (🇨🇦)

**Comment by zeke** [comment]
Done. Took care of the Canadian English issues in https://github.com/electron/electron-i18n/pull/193/commits/2abbd48efcbb023c7b2e99bbf9f81d67f1b21576
