### ISSUE TITLE
Code formatting failed in Crowdin

### ISSUE THREAD

**Issue by TiagoDanin** [electron/electron-i18n#143]
Something has affected the `development/build-instructions-linux.md`
![image](https://user-images.githubusercontent.com/5731176/32691722-173f7144-c6f3-11e7-9e9e-281045e20ffa.png)
(https://electronjs.org/docs/development/build-instructions-linux)

![image](https://user-images.githubusercontent.com/5731176/32691726-324424f8-c6f3-11e7-959e-5f92b6ef7793.png)
- https://crowdin.com/translate/electron/all/en-ptbr#q=bash+%24
- https://crowdin.com/translate/electron/all/en-fr#q=bash+%24
- ... all

**Comment by pierreneter** [comment]
It still ok with my browser (Chrome  62.0.3202.89), 
![captur1e](https://user-images.githubusercontent.com/12815768/32691794-b6b869d2-c73f-11e7-810f-0a57fad7044c.PNG)

**Comment by TiagoDanin** [comment]
@pierreneter 
The English language is not affected. Others using electron-i18n are affected.

**Comment by pierreneter** [comment]
Got it. 👍

**Comment by zeke** [comment]
Looks like those bash code blocks were indented. Here's a fix: https://github.com/electron/electron/pull/11093

**Comment by zeke** [comment]
Closing this, as it will trickle into this rep eventually.
