### ISSUE TITLE
miss word in notification-action.md

### ISSUE THREAD

**Issue by kstar0714** [electron/electron-i18n#160]
one word is miss. content/docs/api/structures/notification-action.md
incomptible -> incompatible
thanks

**Comment by MarshallOfSound** [comment]
Hey @kstar0714, this typo would have to be fixed in the original over at `electron/electron`.  See https://github.com/electron/electron/blob/master/docs/api/structures/notification-action.md

Do you think you could give that a shot? 😄

**Comment by MarshallOfSound** [comment]
Actually, this has already been fixed in the original 🤔 

/cc @zeke Any ideas?

**Comment by kstar0714** [comment]
i`m looking for it. thanks.

**Comment by zeke** [comment]
Yeah we need to run `npm run collect` to bring in the latest changes. That's not automated yet but it will be soon. Related: https://github.com/electron/electronjs.org/issues/830

Also we're only pulling changes from the `latest` stable release of Electron on npm: https://github.com/electron/electron-i18n/issues/81

**Comment by kstar0714** [comment]
Documents of crowdin site and documents of electron-i18n are some different. Please update it.

**Comment by zeke** [comment]
This update will take effect the next time we pull in docs from electron. Closing.
