### ISSUE TITLE
Can I pull requests here?

### ISSUE THREAD

**Issue by duswlsgur** [electron/electron-i18n#164]
I found wrong docs in electron-i18n.
So I see the pull requests, It merged only by zeke and glotbot.

**Comment by zeke** [comment]
English docs in this repo are currently fetched manually from the electron repo's latest stable release (currently 1.7.9). We will be revising and automating this process. For more details on how this will evolve, see https://github.com/electron/electron-i18n/issues/81 and https://github.com/electron/electronjs.org/issues/830

If you wish to help translate the docs, you can safely disregard this repo and go straight to https://crowdin.com/project/electron where you will find plenty of content awaiting translation.
