### ISSUE TITLE
Fix Travis CI for Pull Requests from forked repos

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#165]
https://github.com/electron/electron-i18n/pull/162 is failing because Travis [does not expose its env vars to forks](https://blog.travis-ci.com/2014-08-22-environment-variables/)

> MissingEnvVarsError: The following variables are defined in .env.example but are not defined in the environment: GH_TOKEN, CROWDIN_KEY.

Let's revamp the test suite to not rely on these env vars.

**Comment by sdj01044** [comment]
How about remove these env vars?

**Comment by zeke** [comment]
They're part of the test and build process right now, so it's not just a matter of removing them. But this shouldn't be too hard.
