### ISSUE TITLE
can we have hi-IN translations started?

### ISSUE THREAD

**Issue by sambhav2612** [electron/electron-i18n#174]
so I was looking for Hindi (India) translations but couldn't find any. if possible, could someone add/authorize to add Hindi i18n translations on crowdin

thanks
sambhav

**Comment by zeke** [comment]
Done! Thanks for asking and please open issues here if you have questions or feedback on the translation process.

<img width="829" alt="screen shot 2017-11-27 at 10 20 17 am" src="https://user-images.githubusercontent.com/2289/33282146-95bd78e8-d35c-11e7-8c88-54c0b0cc40b6.png">
