### ISSUE TITLE
Make sure Chinese Traditional and Simplified have the proper native labels

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#194]
Looks like the Chinese native language names are the same here:

<img width="548" alt="screen shot 2017-12-11 at 11 08 24 am" src="https://user-images.githubusercontent.com/2289/33848819-b64682c8-de63-11e7-8d3c-e999d1df5552.png">

@vanessayuenn @zcbenz is one of them wrong? Which one?

We are currently using the [locale-code](https://ghub.io/locale-code) module to get this info, and this wouldn't be the first time that's not exactly right:

https://github.com/electron/electron-i18n/blob/f3cc99dfb6ef27624a693834042fae98904af36b/lib/locales.js#L23

Best long-term answer might be to swap out `locale-code` with a more accurate module.

**Comment by vanessayuenn** [comment]
They are both correct. Tl;dr explanation is that there is a subset of characters that are exactly the same in Traditional Chinese and Simplified Chinese. 😄

**Comment by zeke** [comment]
Nice. Thanks for explaining.
