### ISSUE TITLE
Delete old files

### ISSUE THREAD

**Issue by nzeemin** [electron/electron-i18n#198]
Looking at [this](https://electronjs.org/docs) with Russian as the current language, I see some non-translate-able articles -- they are not listed [here](https://crowdin.com/project/electron/ru):

- https://electronjs.org/docs/tutorial/debugging-main-process-node-inspector
- https://electronjs.org/docs/development/upgrading-chrome

Looks like they are just old/legacy.
Need to delete corresponding files in [here](https://github.com/electron/electron-i18n/tree/master/content/ru-RU/docs).

**Comment by zeke** [comment]
Thanks for letting us know, @nzeemin. 👍 

I just went through this recently when disabling the Canadian locale. It seems Crowdin does not remove old files when syncing with GitHub.

Deleting these Russian files would do the trick for now, but the same issue probably applies to all the other languages now too, so I'd rather fix the underlying issue. The build process in this repo will need to be updated to clean out any leftover files in the target language directories, and we should add an automated test to verify that the file tree for each language is identical to `/content/en-US`.
