### ISSUE TITLE
Conversation with Crowdin

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#215]
We'll be meeting with some folks at Crowdin later this week to share feedback on our experience so far, and to learn how to use Crowdin more effectively on the Electron project.

## Question: How can we prevent translation of certain content?

The [Indonesian translations](https://electronjs.org/languages) currently have a lot of problems. A screenshot illustrates many of them:

<img width="1440" alt="screen shot 2018-01-22 at 1 40 33 pm" src="https://user-images.githubusercontent.com/2289/35246062-3e94e520-ff7a-11e7-9add-55d56ded5e0f.png">

## Question: How do we settle on a given translation?

We're starting to see multiple translation suggestions. How should we handle this? For example, can we apply a voting system that will take effect automatically without intervention?

<img width="558" alt="screen shot 2018-01-11 at 8 42 03 pm" src="https://user-images.githubusercontent.com/2289/35246092-4ea25f56-ff7a-11e7-8ff6-d30f15051f40.png">

## Question: How can we communicate with a given language community?

We want to reach out to our Indonesian translators to collectively seek out solutions to the problem of mistranslated content (and also to thank them for their help!). Is there a way to carry out a language-scoped conversation on Crowdin?

## Question: What is the Context Editor?

https://crowdin.com/translate/electron/9/en-ar#267:ac:86

<img width="825" alt="screen shot 2018-01-23 at 9 20 08 am" src="https://user-images.githubusercontent.com/2289/35290317-bd1ad7e8-001e-11e8-80c2-444982560ea0.png">

## Feature request: Easier deep linking to Translation pages

See https://github.com/zeke/get-crowdin-file-ids

> Imagine you're serving up some Crowdin-translated content on your website and you want to add a link to each page that lets translators jump right into translating that content on the Crowdin site. Unfortunately, the URLs on Crowdin's translation pages are a bit cryptic:
> 
> `https://crowdin.com/translate/electron/56/en-fr`
>
> Here `56` refers to Crowdin's internal id property for a given file.

It would be great if Crowdin accepted URLs that contained _target language_ and _target filename_ as parameters and redirected to the appropriate URL. For example:

```
https://crowdin.com/translate/electron/go?language=en-FR&filenaname=foo.md
```

## Feature request: Delete old files

See https://github.com/electron/electron-i18n/issues/198

**Comment by zeke** [comment]
Notes from the call:

Crowdin can "lock" certain patterns in files. This prevents translators from proposing a translation that changes the locked portion of a string. Our first step will be to prevent translation of code blocks in markdown, both inline code wrapped by single backticks (`), or GitHub Fenced blocks wrapped by three backticks.

When a string has multiple suggestions, the best option is to delegate the choice to proofreaders.

Messaging a group of translators in a specific language is supposed to be possible, but it's buggy. We could get around this by requiring people to be approved as "members" of a language, but Andriy thinks this is not the best option, as it creates a bottleneck for all new translators joining the project. Still an unsolved problem...

For fixing mistakes like `&gt;` being changed to `& gt;`, there is a global find and replace tool in the translator view, with a replace preview mode.

**Comment by dakeshi** [comment]
@zeke I'm adding more info about this issue.

> Crowdin can "lock" certain patterns in files.

Using `hide` feature, you can handle this. You can hide multiple string or a single string.

* hide multiple strings
multiple https://support.crowdin.com/files-management/#strings-management
* hide singe string
![block_translation_hide_string](https://user-images.githubusercontent.com/8563047/35425186-4256afd4-029c-11e8-9ca8-a58e14a08279.png)

> a string has multiple suggestions
Yes. proofreaders can decide it. But it is possible to vote anyone to select what is the best suggestion.

* project roles
https://support.crowdin.com/modifying-project-participants-roles/

* vote feature
https://support.crowdin.com/online-editor/

> How can we communicate with a given language community?
I think that opening slack, gitter, or discord channel is more better approach.

**Comment by zeke** [comment]
Thanks for the info, @dakeshi!

**Comment by zeke** [comment]
The only real action item that emerged from this conversation was the idea of "protected" code blocks that cannot be translated. @Andrulko is there an issue somewhere we can follow to track progress on this?

**Comment by Andrulko** [comment]
@zeke, there is one problem we've encountered when implementing custom tags highlighting for you. All codes are surrounded with <0> or <code> tag and for some technical reasons placeholders highlighting is quite a challenge here. It's still opened and I'll try to push this again. The task is in JIRA which isn't publicly accessible...

**Comment by zeke** [comment]
@Andrulko after some reflection, we are thinking the the best way to solve this problem is not to lock down code snippets, but to do the following:

- promote good translators to proofreader status
- educate new translators #245
- generate a glossary of reserved words, method names, etc. #82 

I'm going to close this issue, and we can open smaller more specific issues as needed.
