### ISSUE TITLE
Using Translation Memory suggestions

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#22]
is there a way to apply translations from the Translation Memory (TM) in bulk? Or to have them applied automatically?

**Comment by yavorysynka** [comment]
Yes, you can use the pre-translate feature and apply 100% and perfect TM matches to newly uploaded strings automatically. 

More information here:
https://support.crowdin.com/translation-memory/#applying-translation-memory-via-pre-translation

**Comment by zeke** [comment]
Can the pre-translation setting be applied automatically? Or does a human have to go to this page every time we want to do that?

**Comment by yavorysynka** [comment]
Yes, they can be applied automatically. 

Please switch to the Recourses -> Workflows -> Create a new workflow. Each step is described here:
https://support.crowdin.com/advanced-workflows/#customizing-the-workflow

**Comment by zeke** [comment]
This has been enabled. See https://github.com/electron/electron-i18n/issues/135
