### ISSUE TITLE
String should not be separated (content/en-US/website/locale.yml)

### ISSUE THREAD

**Issue by ryo-a** [electron/electron-i18n#227]
https://github.com/electron/electron-i18n/blob/c5b556077a82c7d611159b05df92ab8927f86dc3/content/en-US/website/locale.yml#L200
Current string in "search" is separated but this makes translations unnatural. (Some languages such as Japanese have different [word order](https://en.wikipedia.org/wiki/Word_order) from English's one.)
It should be like below.
```
search:
  description: Find Electron resources from <a href="/search/docs">documentation</a>, <a href="/search/npmPackages">npm packages</a> and <a href="/search/repos">GitHub repos</a>.
```

**Comment by zeke** [comment]
Hey @ryo-a thanks for pointing this out. Can you open an issue on electronjs.org? That's where the YML content lives, and where we would open a PR to fix this issue.

**Comment by ryo-a** [comment]
Oops, sorry! I opened it on electronjs.org. 
https://github.com/electron/electronjs.org/issues/1064

**Comment by zeke** [comment]
Thanks 👍
