### ISSUE TITLE
Please check crowdin comment

### ISSUE THREAD

**Issue by dakeshi** [electron/electron-i18n#241]
I left a comment to fix some typo errors in english source files but there are no reply for that and it has not changed yet. 

Would I report those of issue on github issue instead of crowdin comment?

**Comment by vanessayuenn** [comment]
@dakeshi typo fixes in English source content can be made via a PR against https://github.com/electron/electron/tree/master/docs on the electron repo.

**Comment by zeke** [comment]
Sorry we missed your comment on Crowdin, @dakeshi. Like @vanessayuenn said, electron/electron is the place to fix issues in the source content. A pull request would be much appreciated!

**Comment by dakeshi** [comment]
The reason why I leave comments for typo errors instead of github issue, crowdin is uni-directional sync. (from crowdin to github). If you prefer to PR for typo errors, I'll do that.

**Comment by dakeshi** [comment]
I create PR #243 for typo.

**Comment by dakeshi** [comment]
If you give a proof reader role for korean translation, it would be helpful to make better translation.

**Comment by zeke** [comment]
> Would you give a proof reader role for korean translation?

✅ Done. Thanks for helping out!

**Comment by dakeshi** [comment]
Thanks. Here is recreated PR in https://github.com/electron/electron/pull/11918
