### ISSUE TITLE
Use probot to steer folks to Crowdin

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#35]
In https://github.com/electron/electron-i18n/pull/33, a kind user opened a pull request with translated content. Unfortunately this repo is not the source of translated content, but rather the destination. When this happens we should help guide the person to make edits on Crowdin instead.

This sounds like a job for [probot](https://github.com/probot).

cc @bkeepers @lee-dohm

**Comment by lee-dohm** [comment]
You could use https://github.com/probot/autoresponder as a basis for an autoresponding bot for these kinds of PRs. Let me know if you need any help with it!
