### ISSUE TITLE
Litost

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#65]
![photo on 8-22-17 at 4 17 pm 2](https://user-images.githubusercontent.com/2289/29591798-977d1e98-8755-11e7-8004-c247b29360ef.jpg)

@tonyganch @cifratila does this definition do the word justice?

**Comment by tonyganch** [comment]
@alespergl, correct me please.
In my opinion "litost" is translatable, and it means sorrow, pity, regret.
I would even go further and say that sorrow/sorry ("I am sorry") have the same relation as litost/lito ("Je mi lito").

As i understand, the definition above is a loose interpretation of a passage taken from Kundera's book (fiction literature), where Kundera himself says it's untranslatable. I'm not aware of any other sources of this definition who would not quote Kundera.
And my dictionary of contemporary Czech has sorrow and remorse as definition, but no this "untranslatable and too complicated to explain".

**Comment by alespergl** [comment]
The description in the screenshot completely misses the meaning of the word. That feeling it describes would more appropriately be called ["zahanbení."](https://slovnik.seznam.cz/cz-en/?q=zahanben%C3%AD)

["Lítost"](https://slovnik.seznam.cz/en/?q=l%C3%ADtost) is easily translatable (at least in the most common meanings), as @tonyganch correctly said, as pity or grief. I would like to see that passage where Kundera claims it to be untranslatable. Maybe he meant some niche meaning of the word, or maybe it was a different word? 😉

**Comment by tonyganch** [comment]
@alespergl, here is that passage in Russian, Google Translate FTW :)

<details>
Литостъ — чешское слово, непереводимое на другие языки. Его первый слог, произнесенный под ударением и протяжно, звучит как стон брошенной собаки. Для смысла этого слова я напрасно ищу соответствие в других языках, хотя мне и трудно представить себе, как без него может кто-то постичь человеческую душу.

Приведу пример: студент купался со своей подругой— студенткой в реке. Девушка была спортсменкой, а он плавал скверно. Не умел дышать под водой, двигался медленно, судорожно держа голову над поверхностью. Девушка любила его до безумия и была настолько тактична, что старалась плавать так же медленно, как и он. Но когда купание уже близилось к концу, ей захотелось отдаться своему спортивному порыву, и она мощным кролем устремилась к другому берегу. Студент тоже попытался плыть быстрее, но при этом наглотался воды. И, почувствовав себя ничтожным, уличенным в своей физической неполноценности, испытал литостъ. Ему вспомнилось его болезненное детство без спортивных занятий, без друзей, под чрезмерно заботливым присмотром матери, и при мысли о себе и своей жизни его охватило отчаяние. Когда они шли по проселочной дороге к городу, он молчал. Уязвленный и униженный, он ощущал неодолимое желание ее ударить. «Что с тобой?» — спросила его студентка, и он попенял ей: она же прекрасно знает, что на другой стороне реки водовороты, что он запретил ей туда плавать, что там она могла утонуть, — и дал ей пощечину. Девушка расплакалась, и он, видя на ее лице слезы, проникся к ней сочувствием, обнял ее, и его литостъ рассеялась.

Или вот иное переживание из детства студента: родители заставляли его брать уроки скрипки. Он не был особо одаренным, и учитель прерывал его холодным и невыносимым голосом, попрекая за ошибки. Он чувствовал себя униженным, хотелось плакать. Но вместо того, чтобы стараться играть точнее, без ошибок, он, напротив, стал делать их умышленно, и голос учителя звучал еще невыносимее и злобнее, а он все глубже и глубже погружался в свою литостъ.

Итак, что такое литостъ?
Литостъ — мучительное состояние, порожденное видом собственного, внезапно обнаруженного убожества.
</details>

**Comment by zeke** [comment]
Love the feedback on this. Thanks!
