### ISSUE TITLE
Removes the translations made by machine translations in Spanish

### ISSUE THREAD

**Issue by TiagoDanin** [electron/electron-i18n#74]
# Removes the translations made by machine translations in Spanish
Translation made by glotbot used automatic machine translation (#6), 70% need to be retranslated.

**Comment by zeke** [comment]
Done!

Used the technique outlined here: https://github.com/electron/electron-i18n/issues/6#issuecomment-305821143

<img width="1167" alt="screen shot 2017-09-08 at 11 02 47 am" src="https://user-images.githubusercontent.com/2289/30224937-723a1f36-9485-11e7-90cf-bbc4e212a57a.png">

This change might take a few minutes to be reflected on the Crowdin site.

**Comment by zeke** [comment]
These changes made it to the GitHub repo: https://github.com/electron/electron-i18n/pull/76
