### ISSUE TITLE
Surface improvements to tutorials on the website more quickly

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#81]
## Problem

The website currently displays docs from the latest stable version of Electron. The stable version doesn't change very often, and sometimes there are weeks of beta versions before the next stable bump.

While it makes sense for the website's API documentation to strictly match the current stable version of Electron, the tutorial content found in `docs/tutorial` is generally not Electron-version-specific.

Currently we fetch all docs from `latest`:

Files | Source Commitish
--- | ---
`/docs/**/*.md` | electron@latest
`locale.yml` | electron.atom.io#master

Instead, I propose that we fetch `docs/tutorial/**` straight from Electron's master branch:

Files | Source Commitish
--- | ---
`/docs/api/**/*.md` | electron@latest
`/docs/development/**/*.md` | electron@latest
`/docs/tutorial/**/*.md` | electron#master
`locale.yml` | electron.atom.io#master

cc @leo, whose eagerness to see https://github.com/electron/electron/pull/10251 deployed on the website prompted this idea.

**Comment by leo** [comment]
Very good idea! 👍😊
